title: "Creating a silver-annotated dataset from WikiText-TL-39"
description: |
  This project creates a silver-annotated dataset for named-entity recognition
  (NER). It uses another silver-annotated
  [WikiANN](https://huggingface.co/datasets/wikiann) (`wikiann`) dataset to
  train an initial NER model, and then bootstrapped the annotations of a
  larger [WikiText-TL-39](https://huggingface.co/datasets/wikitext_tl39) corpus
  (`wikitext`).

  This results to two NER models, one from the original WikiANN corpus
  (`tl_wikiann_silver`) and another from the WikiText-TL-39 corpus
  (`tl_wikitext_silver`). Evaluation is done by testing these models in a small
  sample of gold annotations done by a native speaker.

vars:
  version: "0.1"
  config: "default_config.cfg"
  gpu_id: 0
  lang: "tl"
  wikiann_silver: "wikiann_silver"
  wikitext_silver: "wikitext_silver"
  wikitext_gold: "wikitext_gold"

directories:
  - "configs"
  - "corpus/raw"
  - "corpus/silver"
  - "corpus/gold"
  - "scripts"
  - "training"
  - "metrics"
  - "package"

workflows:
  all:
    - "download"
    - "train-wikiann"
    - "annotate-silver"
    - "train-wikitext"
    - "evaluate-wikiann"
    - "evaluate-wikitext"
    - "evaluate-gold"
    - "package"

commands:
  - name: "download"
    help: "Download the WikiANN and WikiText-TL-39 datasets from Huggingface"
    script:
      - >-
        python -m scripts.download_datasets
        --wikitext ${vars.wikitext_silver}
        --wikiann ${vars.wikiann_silver}
        --output corpus/
      - "python -m scripts.download_datasets "
    outputs:
      - "corpus/raw/${vars.wikiann_silver}-train.spacy"
      - "corpus/raw/${vars.wikiann_silver}-dev.spacy"
      - "corpus/raw/${vars.wikiann_silver}-test.spacy"
      - "corpus/raw/${vars.wikitext_silver}-train.spacy"
      - "corpus/raw/${vars.wikitext_silver}-dev.spacy"
      - "corpus/raw/${vars.wikitext_silver}-test.spacy"

  - name: "train-wikiann"
    help: "Train a Tagalog NER model from the WikiANN dataset"
    script:
      - >-
        python -m spacy train
        configs/${vars.config}.cfg
        --nlp.lang ${vars.lang}
        --output training/${vars.lang}_${vars.wikiann_silver}/
        --paths.train corpus/raw/${vars.wikiann_silver}-train.spacy
        --paths.dev corpus/raw/${vars.wikiann_silver}-dev.spacy
        --gpu-id ${vars.gpu_id}
    deps:
      - corpus/raw/${vars.wikiann_silver}-train.spacy
      - corpus/raw/${vars.wikiann_silver}-dev.spacy
    outputs:
      - training/${vars.lang}_${vars.wikiann_silver}/

  - name: "annotate-silver"
    help: "Annotate a larger WikiText-TL-39 dataset using the trained model from WikiANN"
    script:
      - >-
        python -m scripts.annotate_silver 
        corpus/raw/${vars.wikitext_silver}-train.spacy
        corpus/raw/${vars.wikitext_silver}-dev.spacy
        corpus/raw/${vars.wikitext_silver}-test.spacy
        --model training/${vars.lang}_${vars.wikiann_silver}/
        --output corpus/silver/
    deps:
      - "corpus/raw/${vars.wikitext_silver}-train.spacy"
      - "corpus/raw/${vars.wikitext_silver}-dev.spacy"
      - "corpus/raw/${vars.wikitext_silver}-test.spacy"
    outputs:
      - "corpus/silver/${vars.wikitext_silver}-train.spacy"
      - "corpus/silver/${vars.wikitext_silver}-dev.spacy"
      - "corpus/silver/${vars.wikitext_silver}-test.spacy"

  - name: "train-wikitext"
    help: "Train a Tagalog NER model from the WikiText dataset"
    script:
      - >-
        python -m spacy train
        configs/${vars.config}.cfg
        --nlp.lang ${vars.lang}
        --output training/${vars.lang}_${vars.wikitext_silver}/
        --paths.train corpus/silver/${vars.wikitext_silver}-train.spacy
        --paths.dev corpus/silver/${vars.wikitext_silver}-dev.spacy
        --gpu-id ${vars.gpu_id}
    deps:
      - corpus/silver/${vars.wikitext_silver}-train.spacy
      - corpus/silver/${vars.wikitext_silver}-dev.spacy
    outputs:
      - training/${vars.lang}_${vars.wikitext_silver}/

  - name: "evaluate-wikiann"
    help: "Evaluate the trained models to the silver-annotated WikiANN test set"
    script:
      - >-
        python -m spacy evaluate 
        training/${vars.lang}_${vars.wikiann_silver}
        corpus/silver/${vars.wikiann_silver}-test.spacy
        --output metrics/${vars.wikiann_silver}/${vars.lang}_${vars.wikiann_silver}.json
      - >-
        python -m spacy evaluate 
        training/${vars.lang}_${vars.wikitext_silver} 
        corpus/silver/${vars.wikiann_silver}-test.spacy
        --output metrics/${vars.wikiann_silver}/${vars.lang}_${vars.wikiann_silver}.json
    deps:
      - training/${vars.lang}_${vars.wikiann_silver}
      - training/${vars.lang}_${vars.wikitext_silver}
      - corpus/silver/${vars.wikiann_silver}-test.spacy
    outputs:
      - metrics/${vars.wikiann_silver}/${vars.lang}_${vars.wikiann_silver}.json
      - metrics/${vars.wikiann_silver}/${vars.lang}_${vars.wikitext_silver}.json

  - name: "evaluate-wikitext"
    help: "Evaluate the trained models to the silver-annotated WikiText test set"
    script:
      - >-
        python -m spacy evaluate 
        training/${vars.lang}_${vars.wikiann_silver}
        corpus/silver/${vars.wikitext_silver}-test.spacy
        --output metrics/${vars.wikitext_silver}/${vars.lang}_${vars.wikiann_silver}.json
      - >-
        python -m spacy evaluate 
        training/${vars.lang}_${vars.wikitext_silver} 
        corpus/silver/${vars.wikitext_silver}-test.spacy
        --output metrics/${vars.wikitext_silver}/${vars.lang}_${vars.wikiann_silver}.json
    deps:
      - training/${vars.lang}_${vars.wikiann_silver}
      - training/${vars.lang}_${vars.wikitext_silver}
      - corpus/silver/${vars.wikitext_silver}-test.spacy
    outputs:
      - metrics/${vars.wikitext_silver}/${vars.lang}_${vars.wikiann_silver}.json
      - metrics/${vars.wikitext_silver}/${vars.lang}_${vars.wikitext_silver}.json

  - name: "evaluate-gold"
    help: "Evaluate the trained models on an annotated subset of WikiText"
    script:
      - >-
        python -m spacy evaluate 
        training/${vars.lang}_${vars.wikiann_silver}
        corpus/gold/${vars.wikitext_gold}-test.spacy
        --output metrics/${vars.wikitext_gold}/${vars.lang}_${vars.wikiann_silver}.json
      - >-
        python -m spacy evaluate 
        training/${vars.lang}_${vars.wikitext_silver} 
        corpus/gold/${vars.wikitext_gold}-test.spacy
        --output metrics/${vars.wikitext_gold}/${vars.lang}_${vars.wikiann_silver}.json
    deps:
      - training/${vars.lang}_${vars.wikiann_silver}
      - training/${vars.lang}_${vars.wikitext_silver}
      - corpus/gold/${vars.wikitext_gold}-test.spacy
    outputs:
      - metrics/${vars.wikitext_gold}/${vars.lang}_${vars.wikiann_silver}.json
      - metrics/${vars.wikitext_gold}/${vars.lang}_${vars.wikitext_silver}.json

  - name: "package"
    help: "Package the trained models from the silver-annotated datasets"
    script:
      - >-
        python -m spacy package training/${vars.lang}_${vars.wikiann_silver} packages/
        --name ${vars.wikiann_silver}
        --version ${vars.version}
        --force
      - >-
        python -m spacy package training/${vars.lang}_${vars.wikitext_silver} packages/
        --name ${vars.wikitext_silver}
        --version ${vars.version}
        --force
    outputs_no_cache:
      - packages/${vars.lang}_${vars.wikiann_silver}-${vars.version}/dist/${vars.lang}_${vars.wikiann_silver}-${vars.version}.tar.gz
      - packages/${vars.lang}_${vars.wikitext_silver}-${vars.version}/dist/${vars.lang}_${vars.wikitext_silver}-${vars.version}.tar.gz
