title: "Creating a silver-standard dataset from the TLUnified Tagalog corpus"
description: |
  This project creates, `tl_calamancy_silver_corpus` a silver-standard dataset for
  named-entity recognition (NER). It uses another silver-annotated
  [WikiANN](https://huggingface.co/datasets/wikiann) (`wikiann`) dataset to train an
  initial NER model, and then bootstrapped the annotations of a larger
  [TLUnified](https://arxiv.org/abs/2111.06053) corpus (`tlunified`).

  For evaluation, I trained two NER models, one from the original WikiANN corpus
  (`tl_wikiann_silver`) and another from the TLUnified corpus
  (`tl_tlunified_silver`). I then tested them against a small sample of
  tlunified's data annotated by me, a native speaker.

vars:
  version: 0.0.0
  config: "default.cfg"
  gpu_id: 0
  lang: "tl"
  wikiann_silver: "wikiann_silver"
  tlunified_silver: "tlunified_silver"
  tlunified_gold: "tlunified_gold"

directories:
  - "assets"
  - "configs"
  - "corpus/raw"
  - "corpus/silver"
  - "corpus/gold"
  - "scripts"
  - "training"
  - "metrics"
  - "package"

workflows:
  all:
    - "download-wikiann"
    - "process-tlunified"
    - "train-wikiann"
    - "annotate-silver"
    - "train-tlunified"
    - "cross-evaluate-wikiann"
    - "cross-evaluate-tlunified"
    - "cross-evaluate-gold"
    - "package"
  wikiann:
    - "download-wikiann"
    - "train-wikiann"
    - "evaluate-wikiann"

assets:
  - dest: "assets/tlunified.zip"
    url: "https://s3.us-east-2.amazonaws.com/blaisecruz.com/datasets/tlunified/tlunified.zip"
    description: "TLUnified dataset (from Improving Large-scale Language Models and Resources for Filipino by Cruz and Cheng 2022)"

commands:
  - name: "download-wikiann"
    help: "Download the WikiANN dataset from HuggingFace and save to spaCy format"
    script:
      - >-
        python -m scripts.download_wikiann
        --filename ${vars.wikiann_silver}
        --output-dir corpus/silver/
        --gpu-id ${vars.gpu_id}
        --verbose
    outputs:
      - "corpus/silver/${vars.wikiann_silver}-train.spacy"
      - "corpus/silver/${vars.wikiann_silver}-validation.spacy"
      - "corpus/silver/${vars.wikiann_silver}-test.spacy"

  - name: "process-tlunified"
    help: "Convert the TLUnified dataset to the spaCy format"
    script:
      - unzip assets/tlunified.zip -d assets/
      - >-
        python -m scripts.process_tlunified assets/tlunified/train.txt
        --filename ${vars.tlunified_silver}
        --output-dir corpus/raw/
        --gpu-id ${vars.gpu_id}
        --segment
        --shuffle
        --verbose
    deps:
      - "assets/tlunified.zip"
    outputs:
      - "corpus/raw/${vars.tlunified_silver}-train.spacy"
      - "corpus/raw/${vars.tlunified_silver}-validation.spacy"
      - "corpus/raw/${vars.tlunified_silver}-test.spacy"

  - name: "train-wikiann"
    help: "Train a Tagalog NER model from the WikiANN dataset"
    script:
      - >-
        python -m spacy train
        configs/${vars.config}
        --nlp.lang ${vars.lang}
        --output training/${vars.lang}_${vars.wikiann_silver}/
        --paths.train corpus/silver/${vars.wikiann_silver}-train.spacy
        --paths.dev corpus/silver/${vars.wikiann_silver}-validation.spacy
        --gpu-id ${vars.gpu_id}
    deps:
      - corpus/silver/${vars.wikiann_silver}-train.spacy
      - corpus/silver/${vars.wikiann_silver}-validation.spacy
    outputs:
      - training/${vars.lang}_${vars.wikiann_silver}/

  - name: "annotate-silver"
    help: "Annotate a larger TLUnified dataset using the trained model from WikiANN"
    script:
      - >-
        python -m scripts.annotate 
        corpus/raw/${vars.tlunified_silver}-train.spacy
        corpus/raw/${vars.tlunified_silver}-validation.spacy
        corpus/raw/${vars.tlunified_silver}-test.spacy
        --model-path training/${vars.lang}_${vars.wikiann_silver}/
        --output-dir corpus/silver/
        --gpu-id ${vars.gpu_id}
        --verbose
    deps:
      - "corpus/raw/${vars.tlunified_silver}-train.spacy"
      - "corpus/raw/${vars.tlunified_silver}-validation.spacy"
      - "corpus/raw/${vars.tlunified_silver}-test.spacy"
    outputs:
      - "corpus/silver/${vars.tlunified_silver}-train.spacy"
      - "corpus/silver/${vars.tlunified_silver}-validation.spacy"
      - "corpus/silver/${vars.tlunified_silver}-test.spacy"

  - name: "train-tlunified"
    help: "Train a Tagalog NER model from the tlunified dataset"
    script:
      - >-
        python -m spacy train
        configs/${vars.config}
        --nlp.lang ${vars.lang}
        --output training/${vars.lang}_${vars.tlunified_silver}/
        --paths.train corpus/silver/${vars.tlunified_silver}-train.spacy
        --paths.dev corpus/silver/${vars.tlunified_silver}-validation.spacy
        --gpu-id ${vars.gpu_id}
    deps:
      - corpus/silver/${vars.tlunified_silver}-train.spacy
      - corpus/silver/${vars.tlunified_silver}-validation.spacy
    outputs:
      - training/${vars.lang}_${vars.tlunified_silver}/

  - name: "evaluate-wikiann"
    help: "Evaluate WikiANN to its test set"
    script:
      - mkdir -p metrics/${vars.wikiann_silver}/
      - >-
        python -m spacy evaluate 
        training/${vars.lang}_${vars.wikiann_silver}/model-best/
        corpus/silver/${vars.wikiann_silver}-test.spacy
        --output metrics/${vars.wikiann_silver}/${vars.lang}_${vars.wikiann_silver}.json
        --gpu-id ${vars.gpu_id}
    deps:
      - training/${vars.lang}_${vars.wikiann_silver}
      - corpus/silver/${vars.wikiann_silver}-test.spacy
    outputs:
      - metrics/${vars.wikiann_silver}/${vars.lang}_${vars.wikiann_silver}.json

  - name: "evaluate-tlunified"
    help: "Evaluate TLUnified to its test set"
    script:
      - mkdir -p metrics/${vars.tlunified_silver}/
      - >-
        python -m spacy evaluate 
        training/${vars.lang}_${vars.tlunified_silver}/model-best/ 
        corpus/silver/${vars.tlunified_silver}-test.spacy
        --output metrics/${vars.tlunified_silver}/${vars.lang}_${vars.wikiann_silver}.json
        --gpu-id ${vars.gpu_id}
    deps:
      - training/${vars.lang}_${vars.tlunified_silver}
      - corpus/silver/${vars.tlunified_silver}-test.spacy
    outputs:
      - metrics/${vars.tlunified_silver}/${vars.lang}_${vars.tlunified_silver}.json

  - name: "cross-evaluate-wikiann"
    help: "Evaluate the trained models to the silver-annotated WikiANN test set"
    script:
      - mkdir -p metrics/${vars.wikiann_silver}/
      - >-
        python -m spacy evaluate 
        training/${vars.lang}_${vars.wikiann_silver}/model-best/
        corpus/silver/${vars.wikiann_silver}-test.spacy
        --output metrics/${vars.wikiann_silver}/${vars.lang}_${vars.wikiann_silver}.json
        --gpu-id ${vars.gpu_id}
      - >-
        python -m spacy evaluate 
        training/${vars.lang}_${vars.tlunified_silver}/model-best/
        corpus/silver/${vars.wikiann_silver}-test.spacy
        --output metrics/${vars.wikiann_silver}/${vars.lang}_${vars.tlunified_silver}.json
        --gpu-id ${vars.gpu_id}
    deps:
      - training/${vars.lang}_${vars.wikiann_silver}
      - training/${vars.lang}_${vars.tlunified_silver}
      - corpus/silver/${vars.wikiann_silver}-test.spacy
    outputs:
      - metrics/${vars.wikiann_silver}/${vars.lang}_${vars.wikiann_silver}.json
      - metrics/${vars.wikiann_silver}/${vars.lang}_${vars.tlunified_silver}.json

  - name: "cross-evaluate-tlunified"
    help: "Evaluate the trained models to the silver-annotated tlunified test set"
    script:
      - mkdir -p metrics/${vars.tlunified_silver}/
      - >-
        python -m spacy evaluate 
        training/${vars.lang}_${vars.wikiann_silver}/model-best/
        corpus/silver/${vars.tlunified_silver}-test.spacy
        --output metrics/${vars.tlunified_silver}/${vars.lang}_${vars.wikiann_silver}.json
        --gpu-id ${vars.gpu_id}
      - >-
        python -m spacy evaluate 
        training/${vars.lang}_${vars.tlunified_silver}/model-best/
        corpus/silver/${vars.tlunified_silver}-test.spacy
        --output metrics/${vars.tlunified_silver}/${vars.lang}_${vars.tlunified_silver}.json
        --gpu-id ${vars.gpu_id}
    deps:
      - training/${vars.lang}_${vars.wikiann_silver}
      - training/${vars.lang}_${vars.tlunified_silver}
      - corpus/silver/${vars.tlunified_silver}-test.spacy
    outputs:
      - metrics/${vars.tlunified_silver}/${vars.lang}_${vars.wikiann_silver}.json
      - metrics/${vars.tlunified_silver}/${vars.lang}_${vars.tlunified_silver}.json

  - name: "cross-evaluate-gold"
    help: "Evaluate the trained models on an annotated subset of tlunified"
    script:
      - mkdir -p metrics/${vars.tlunified_gold}/
      - >-
        python -m spacy evaluate 
        training/${vars.lang}_${vars.wikiann_silver}/model-best/
        corpus/gold/${vars.tlunified_gold}-test.spacy
        --output metrics/${vars.tlunified_gold}/${vars.lang}_${vars.wikiann_silver}.json
        --gpu-id ${vars.gpu_id}
      - >-
        python -m spacy evaluate 
        training/${vars.lang}_${vars.tlunified_silver}/model-best/
        corpus/gold/${vars.tlunified_gold}-test.spacy
        --output metrics/${vars.tlunified_gold}/${vars.lang}_${vars.tlunified_silver}.json
        --gpu-id ${vars.gpu_id}
    deps:
      - training/${vars.lang}_${vars.wikiann_silver}
      - training/${vars.lang}_${vars.tlunified_silver}
      - corpus/gold/${vars.tlunified_gold}-test.spacy
    outputs:
      - metrics/${vars.tlunified_gold}/${vars.lang}_${vars.wikiann_silver}.json
      - metrics/${vars.tlunified_gold}/${vars.lang}_${vars.tlunified_silver}.json

  - name: "package"
    help: "Package the trained models from the silver-annotated datasets"
    script:
      - >-
        python -m spacy package training/${vars.lang}_${vars.wikiann_silver}/model-best/ packages/
        --name ${vars.wikiann_silver}
        --version ${vars.version}
        --force
      - >-
        python -m spacy package training/${vars.lang}_${vars.tlunified_silver}/model-best/ packages/
        --name ${vars.tlunified_silver}
        --version ${vars.version}
        --force
    outputs_no_cache:
      - packages/${vars.lang}_${vars.wikiann_silver}-${vars.version}/dist/${vars.lang}_${vars.wikiann_silver}-${vars.version}.tar.gz
      - packages/${vars.lang}_${vars.tlunified_silver}-${vars.version}/dist/${vars.lang}_${vars.tlunified_silver}-${vars.version}.tar.gz
