title: "Benchmarking gold-annotated TLUnified data"

vars:
  seed: 42
  dataset_version: 1.0
  gpu_id: 0
  lang: "tl"

directories:
  - "assets"
  - "configs"
  - "corpus"
  - "scripts"
  - "training"
  - "metrics"

assets:
  - dest: assets/tl_tlunified_gold_v${vars.dataset_version}.jsonl
    url: "https://storage.googleapis.com/ljvmiranda/calamanCy/tl_tlunified_gold/v${vars.dataset_version}/tl_tlunified_gold.jsonl"
    description: "Annotated TLUnified dataset"

commands:
  - name: "preprocess"
    help: "Preprocess the raw annotated data and convert into spaCy format"
    script:
      - >-
        python -m scripts.preprocess
        assets/tl_tlunified_gold_v${vars.dataset_version}.jsonl corpus/
        --seed ${vars.seed}
        --shuffle
