name: Core tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths-ignore:
      - "*.md"
  workflow_dispatch:

env:
  MODULE_NAME: "calamancy"
  RUN_LINTER: "false"

jobs:
  run:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python_version: ["3.11"]
        include:
          - os: ubuntu-20.04
            python_version: "3.6"
          - os: windows-latest
            python_version: "3.7"
          - os: macos-latest
            python_version: "3.8"
          - os: ubuntu-latest
            python_version: "3.9"
          - os: windows-latest
            python_version: "3.10"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Build distributable (sdist)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U build pip setuptools
          python -m pip install .[dev]
          python -m build --sdist

      - name: Run linter checks
        shell: bash
        if: ${{ env.RUN_LINTER == "true" }}
        run: |
          ruff check .
          python -m mypy $MODULE_NAME

      - name: Delete source directory and install from sdist
        shell: bash
        run: |
          rm -rf $MODULE_NAME
          python -m pip freeze > installed.txt
          python -m pip uninstall -y -r installed.txt
          SDIST=$(python -c "import os;print(os.listdir('./dist')[-1])" 2>&1)
          python -m pip install dist/$SDIST

      - name: Test import
        shell: bash
        run: |
          python -c "import $MODULE_NAME" -Werror

      - name: "Run tests"
        shell: bash
        run: |
          python -m pytest --pyargs $MODULE_NAME
